In [1]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

In [2]:
crime_records = pd.read_csv('../Data/Crime_Records.csv')
len(crime_records)

898199

In [3]:
crime_records

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/13 11:41:00 PM,2023/03/13,23:41,2023,Monday,2023/03/13 11:41:00 PM,125373607041,1253736,230167874,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/13 01:16:00 PM,2023/03/13,13:16,2023,Monday,2023/03/13 01:17:00 PM,125357107041,1253571,220343896,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898194,2023/03/22 01:30:00 PM,2023/03/22,13:30,2023,Wednesday,2023/03/22 01:35:00 PM,125685303401,1256853,230201949,230811847.0,...,-122.406336,POINT (-122.40633623830558 37.75300402962228),54.0,NaN,NaN,NaN,3.0,NaN,2.0,3.0
898195,2023/03/22 12:13:00 AM,2023/03/22,00:13,2023,Wednesday,2023/03/22 12:13:00 AM,125665206371,1256652,230200838,230810020.0,...,-122.440624,POINT (-122.44062361999508 37.78899525864335),102.0,NaN,NaN,NaN,NaN,NaN,6.0,4.0
898196,2023/03/21 09:19:00 PM,2023/03/21,21:19,2023,Tuesday,2023/03/21 10:16:00 PM,125664272000,1256642,230200800,230803734.0,...,-122.452665,POINT (-122.45266472219633 37.70880633652071),66.0,NaN,NaN,NaN,NaN,NaN,1.0,9.0
898197,2023/03/22 03:28:00 PM,2023/03/22,15:28,2023,Wednesday,2023/03/22 05:51:00 PM,125687306303,1256873,230202486,230812680.0,...,-122.405574,POINT (-122.40557374633903 37.790565236529574),19.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0
898198,2023/03/21 05:42:00 PM,2023/03/21,17:42,2023,Tuesday,2023/03/22 09:40:00 AM,125676707021,1256767,230201450,230811015.0,...,-122.402056,POINT (-122.40205647302719 37.72127745117722),91.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0

In [4]:
crime_records = crime_records[['Incident ID', 'Incident Description', 'Incident Datetime', 'Incident Day of Week', 'Incident Category', 'Incident Subcategory', 'Report Datetime', 'Report Type Code','Report Type Description', 'Police District', 'Latitude', 'Longitude', 'Resolution']]
   
# some transformations
crime_records['Incident Datetime'] = pd.to_datetime(crime_records['Incident Datetime'])
crime_records['Report Datetime'] = pd.to_datetime(crime_records['Report Datetime'])
crime_records['Incident Category'] = crime_records['Incident Category'].apply(str)
crime_records['Incident Subcategory'] = crime_records['Incident Subcategory'].apply(str)
crime_records['Incident Description'] = crime_records['Incident Description'].apply(lambda d: d.replace(',', '-') )
crime_records['Incident Category'] = crime_records['Incident Category'].apply(lambda d: d.replace(',', '-') )
crime_records['Incident Subcategory'] = crime_records['Incident Subcategory'].apply(lambda d: d.replace(',', '-') )
crime_records['Incident Category'].fillna('', inplace=True)
crime_records['Incident Subcategory'].fillna('', inplace=True)
crime_records.drop_duplicates(inplace=True)
crime_records.loc[crime_records['Incident Category']=='nan', ['Incident Subcategory', 'Incident Category']] = ''

In [5]:
crime_records

,Incident ID,Incident Description,Incident Datetime,Incident Day of Week,Incident Category,Incident Subcategory,Report Datetime,Report Type Code,Report Type Description,Police District,Latitude,Longitude,Resolution
0,1253736,Vehicle- Recovered- Auto,2023-03-13 23:41:00,Monday,Recovered Vehicle,Recovered Vehicle,2023-03-13 23:41:00,VS,Vehicle Supplement,Out of SF,NaN,NaN,Open or Active
1,1253795,Theft- Other Property- >$950,2023-03-01 05:02:00,Wednesday,Larceny Theft,Larceny Theft - Other,2023-03-11 15:40:00,II,Coplogic Initial,Mission,NaN,NaN,Open or Active
2,1253571,Vehicle- Recovered- Auto,2023-03-13 13:16:00,Monday,Recovered Vehicle,Recovered Vehicle,2023-03-13 13:17:00,VS,Vehicle Supplement,Out of SF,NaN,NaN,Open or Active
3,1253551,Vehicle- Recovered- Auto,2023-03-13 10:59:00,Monday,Recovered Vehicle,Recovered Vehicle,2023-03-13 11:00:00,VS,Vehicle Supplement,Out of SF,NaN,NaN,Open or Active
4,1254024,Vehicle- Recovered- Auto,2023-03-14 18:44:00,Tuesday,Recovered Vehicle,Recovered Vehicle,2023-03-14 18:45:00,VS,Vehicle Supplement,Out of SF,NaN,NaN,Open or Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...
898194,1256853,Shoplifting- Force against Agent,2023-03-22 13:30:00,Wednesday,Robbery,Robbery - Commercial,2023-03-22 13:35:00,II,Initial,Mission,37.753004,-122.406336,Cite or Arrest Adult
898195,1256652,Theft- Other Property- <$50,2023-03-22 00:13:00,Wednesday,Larceny Theft,Larceny Theft - Other,2023-03-22 00:13:00,II,Initial,Northern,37.788995,-122.440624,Cite or Arrest Adult
898196,1256642,Found Property,2023-03-21 21:19:00,Tuesday,Non-Criminal,Non-Criminal,2023-03-21 22:16:00,II,Initial,Ingleside,37.708806,-122.452665,Open or Active
898197,1256873,Theft- From Building- $200-$950,2023-03-22 15:28:00,Wednesday,Larceny Theft,Larceny Theft - From Building,2023-03-22 17:51:00,II,Initial,Central,37.790565,-122.405574,Open or Active
898198,1256767,Vehicle- Stolen- Auto,2023-03-21 17:42:00,Tuesday,Motor Vehicle Theft,Motor Vehicle Theft,2023-03-22 09:40:00,VI,Vehicle Initial,Bayview,37.721277,-122.402056,Open or Active